name: frontend_easy_api
version: 1.0.0
description: OpenAPI API client
homepage: homepage


environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  dio: '^5.7.0'
  one_of: '>=1.5.0 <2.0.0'
  one_of_serializer: '>=1.5.0 <2.0.0'
  built_value: '>=8.4.0 <9.0.0'
  built_collection: '>=5.1.1 <6.0.0'
  json_annotation: '^4.9.0'

dev_dependencies:
  built_value_generator: '>=8.4.0 <9.0.0'
  build_runner: any
  json_serializable: '^6.9.3'
  test: '^1.16.0'
